### PR TITLE
add table node, table example

### PR DESCRIPTION
**Pull request by gavin1990**
add table node, table example

### CODE REVIEW

**Comment by gavin1990** [comment]
This merge is mainly to increase the Table node, there are examples

**Comment by erickwilder** [comment]
I'm not sure if disabling an eslint rule is the best way to fix it's violations.

**Comment by gavin1990** [comment]
Ok, I am modifying my code. @erickwilder

**Comment by beeplin** [comment]
Hey guys~  I am just looking for a tiptap extension for plain html tables and found this. How is the status of this PR?

**Pull request closed without merging**
