### PR TITLE
feat(tiptap): Add TypeScript type definitions for `tiptap` package.

### PR DESCRIPTION
**Pull request by erickwilder**
This PR adds some basic TypeScript type definitions for the `tiptap`  package. I decided to open separate PRs for each package as I can collect early feedback about it and learn in the process so that the next packages have better definitions.

I intentionally added the most basic form here and I _really_ need some guidance/reviews from someone with more experience with it.

### CODE REVIEW

**Comment by philippkuehn** [comment]
Hey @erickwilder, thank you very much for this one. 👍 Currently I'm planning of how to replace scoped slots with components in v1.0. And I think this will need a complete rewrite of this package so maybe it makes more sense to wait for this PR?

**Comment by erickwilder** [comment]
Yeah. I'm fine with that.

**Comment by whosdustin** [comment]
I love the approach of rewriting and adding Typings to the v1.0. Is there a schedule of when that will happen? If not soon, @erickwilder would you have a suggestion on how to add these typings to a current project?

**Comment by yekver** [comment]
Is there any chance this PR will ever be merged? It's really painful to use tiptap with TS without type defs right now :(

**Pull request closed without merging**
